name: applicazionedefinitiva
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  cloud_firestore: ^4.17.5
  date_field: ^5.0.1
  email_validator: ^2.1.17
  file_picker: ^8.0.3
  firebase_auth: ^4.20.0
  firebase_core: ^2.32.0
  firebase_storage: ^11.7.7
  flutter:
    sdk: flutter
  flutter_carousel_widget: ^2.2.0
  numberpicker: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - asset/
  
